### ISSUE TITLE
Can't Process example in ExpansionHunter

### ISSUE THREAD

**Issue by JackChuangTaiwan** [Illumina/REViewer#14]
Here is my command
../REViewer/build/install/bin/REViewer --reads example/output/repeats_realigned.srt.bam --vcf example/output/repeats.vcf --reference example/input/reference.fa --catalog example/input/variants.json  --locus SNV_AND_STR --output-prefix test

Here is response
[2021-03-23 08:54:23.506] [info] Loading specification of locus SNV_AND_STR
[2021-03-23 08:54:23.537] [info] Extracted 549 frags
[2021-03-23 08:54:23.537] [info] Calculating fragment length
[2021-03-23 08:54:23.538] [info] Fragment length is estimated to be 351
[2021-03-23 08:54:23.538] [info] Extracting genotype paths
REViewer: /home/missionbio/REViewer/reviewer/app/GenotypePaths.cpp:106: std::map<std::pair<unsigned int, unsigned int>, std::vector<std::vector<unsigned int> > > getVariantPathPieces(int, const string&, const LocusSpecification&): Assertion `variantSpec.classification().type == VariantType::kRepeat' failed.
Aborted (core dumped)

REViewer v0.2.1
ExpansionHunter v4.0.2 / v3.1.2/ v3.2.0

**Comment by JackChuangTaiwan** [comment]
I have tried method #11 , however it can't solve this issue.

**Comment by egor-dolzhenko** [comment]
Thanks for reporting the issue! Unfortunately REViewer does not yet support indels or SNVs -- it only works on regions containing STRs. Could you please try this example: [input.zip](https://github.com/Illumina/REViewer/files/6187068/input.zip)?

```bash
./REViewer \
  --reads input/repeats_realigned.bam \
  --vcf input/repeats.vcf \
  --reference input/reference.fa \
  --catalog input/variants.json \
  --locus STR \
  --output-prefix output/plot
```

**Comment by JackChuangTaiwan** [comment]
Thanks  I have tried this way and it works.
I will use the input to modify example of ExpansionHunter
