### ISSUE TITLE
What is the difference between GraphAlignmentViewer and REViewer?

### ISSUE THREAD

**Issue by fjmuzengyiheng** [Illumina/REViewer#17]
Sorry, I used to apply GraphAlignmentViewer for STR visualization.
So, what is the difference between GraphAlignmentViewer and REViewer?
Thank you!

**Comment by egor-dolzhenko** [comment]
Thanks for the question! GraphAlignmentViewer is designed to visualize reads grouped by the size of the repeat that they overlap. REViewer is designed to determine and visualize the actual haplotype sequences together with the corresponding read alignments.

The outputs of both programs should be similar for regions containing a single repeat. But for regions containing two or more repeats, REViewer visualizations should be much easier to interpret.

To better understand the differences between GraphAlignmentViewer and REViewer it might be helpful to visualize a few repeat regions (say, a region with one repeat and a region with two repeats) using both programs.

I hope this helps! Please let me know if you have any follow up questions or if you find anything that we can improve.

**Comment by fjmuzengyiheng** [comment]
> Thanks for the question! GraphAlignmentViewer is designed to visualize reads grouped by the size of the repeat that they overlap. REViewer is designed to determine and visualize the actual haplotype sequences together with the corresponding read alignments.
> 
> The outputs of both programs should be similar for regions containing a single repeat. But for regions containing two or more repeats, REViewer visualizations should be much easier to interpret.
> 
> To better understand the differences between GraphAlignmentViewer and REViewer it might be helpful to visualize a few repeat regions (say, a region with one repeat and a region with two repeats) using both programs.
> 
> I hope this helps! Please let me know if you have any follow up questions or if you find anything that we can improve.



Thank you for replying patiently. (By the way, the expansionhunter series are really gooood tools!)
