### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by hchetia** [Illumina/REViewer#20]
HI @egor-dolzhenko 
I am trying to install REViewer in MACOS using the source file.
However, I am running into the foll. error. which is probably related with Boost libraries-

Scanning dependencies of target Boost
[ 42%] Creating directories for 'Boost'
[ 45%] Performing download step (download, verify and extract) for 'Boost'
-- Downloading...
   dst='/Users/hasnahana/Downloads/REViewer-0.1.1/build/Boost-prefix/src/boost_1_73_0.tar.bz2'
   timeout='none'
-- Using src='https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2'
-- Retrying...
-- Using src='https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2'
CMake Error at Boost-stamp/download-Boost.cmake:159 (message):
  Each download failed!

    error: downloading 'https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 52.38.32.109:443...

  TCP_NODELAY set

  Connected to dl.bintray.com (52.38.32.109) port 443 (#0)

  ALPN, offering http/1.1

  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

  ALPN, server did not agree to a protocol

  Server certificate: *.bintray.com

  Server certificate: GeoTrust RSA CA 2018

  Server certificate: DigiCert Global Root CA

  GET /boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2 HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.65.0

  Accept: */*

  

  Mark bundle as not supporting multiuse

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 35.164.5.2:443...

  TCP_NODELAY set

  Connected to dl.bintray.com (35.164.5.2) port 443 (#0)

  ALPN, offering http/1.1

  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

  ALPN, server did not agree to a protocol

  Server certificate: *.bintray.com

  Server certificate: GeoTrust RSA CA 2018

  Server certificate: DigiCert Global Root CA

  GET /boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2 HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.65.0

  Accept: */*

  

  Mark bundle as not supporting multiuse

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 35.164.5.2:443...

  TCP_NODELAY set

  Connected to dl.bintray.com (35.164.5.2) port 443 (#0)

  ALPN, offering http/1.1

  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

  ALPN, server did not agree to a protocol

  Server certificate: *.bintray.com

  Server certificate: GeoTrust RSA CA 2018

  Server certificate: DigiCert Global Root CA

  GET /boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2 HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.65.0

  Accept: */*

  

  Mark bundle as not supporting multiuse

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 35.164.5.2:443...

  TCP_NODELAY set

  Connected to dl.bintray.com (35.164.5.2) port 443 (#0)

  ALPN, offering http/1.1

  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

  ALPN, server did not agree to a protocol

  Server certificate: *.bintray.com

  Server certificate: GeoTrust RSA CA 2018

  Server certificate: DigiCert Global Root CA

  GET /boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2 HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.65.0

  Accept: */*

  

  Mark bundle as not supporting multiuse

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 35.164.5.2:443...

  TCP_NODELAY set

  Connected to dl.bintray.com (35.164.5.2) port 443 (#0)

  ALPN, offering http/1.1

  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

  ALPN, server did not agree to a protocol

  Server certificate: *.bintray.com

  Server certificate: GeoTrust RSA CA 2018

  Server certificate: DigiCert Global Root CA

  GET /boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2 HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.65.0

  Accept: */*

  

  Mark bundle as not supporting multiuse

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 35.164.5.2:443...

  TCP_NODELAY set

  Connected to dl.bintray.com (35.164.5.2) port 443 (#0)

  ALPN, offering http/1.1

  TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

  ALPN, server did not agree to a protocol

  Server certificate: *.bintray.com

  Server certificate: GeoTrust RSA CA 2018

  Server certificate: DigiCert Global Root CA

  GET /boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2 HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.65.0

  Accept: */*

  

  Mark bundle as not supporting multiuse

  The requested URL returned error: 403 Forbidden

  Closing connection 0

  

         --- LOG END ---
         
    

make[2]: *** [Boost-prefix/src/Boost-stamp/Boost-download] Error 1
make[1]: *** [CMakeFiles/Boost.dir/all] Error 2
make: *** [all] Error 2

**Comment by egor-dolzhenko** [comment]
Thanks @hchetia. Could you please check if it works now?

Also, if your data is stored on a Linux cluster, you could run REViewer there using the Linux binary included in the [latest release](https://github.com/Illumina/REViewer/releases/tag/v0.1.1).

**Comment by hchetia** [comment]
Hi @egor-dolzhenko 
Do I download the source file again?
Yes, my data is on a linux cluster.

**Comment by hchetia** [comment]
I re-downloaded and followed the steps of installation, but got the same error.
The cmake script is not able to access the boost library download link.
![image](https://user-images.githubusercontent.com/64626735/127348774-1c090d8b-80f3-44d5-9439-84b583cb1485.png)

**Comment by egor-dolzhenko** [comment]
Hi @hchetia. The latest version of the code contains the updated link: `https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.bz2`.

Could you please completely erase the old source files and then re-download everything again with
`git clone https://github.com/Illumina/REViewer.git`?

The build script may have hashed the old download link.

**Comment by hchetia** [comment]
And successfully installed. Thanks @egor-dolzhenko

**Comment by egor-dolzhenko** [comment]
Glad to hear it!
