### ISSUE TITLE
Bamlet generation for Reviewer viewing

### ISSUE THREAD

**Issue by hchetia** [Illumina/REViewer#21]
Hi Egor,
I am generating bamlets to generate plots using Reviewer to support Expansion hunter results. EH generates a new bam file with the extension "_realigned.bam". Is that the BAMlet? 
Should I use that file or use my original bam file as input for makebamlet.py (EHDN) to make bamlets for my desired genes?
-Hasna

**Comment by hchetia** [comment]
Using the sorted and indexed realigned.bam file showed the following error-
![image](https://user-images.githubusercontent.com/64626735/128422620-a3cb81fe-1f36-4764-b1e6-f92aec6931bb.png)


So, I went ahead with my original bam files to generate bamlets and then using it with REviewer.
Then I ran into a different error- "Unexpected auxiliary tag NM:C"
![image](https://user-images.githubusercontent.com/64626735/128422565-167dd752-0934-430b-9cc9-473708a185ca.png)

-Hasna

**Comment by egor-dolzhenko** [comment]
Hi Hasna,

Sorry for the late reply!

Yes, REViewer uses BAMlets generated by ExpansionHunter ("_realigned.bam"). It would not work with any other kind of BAM file.

Would you be able to share the BAMlet that caused the error? If yes, please feel free to send it to my email (edolzhenko@illumina.com).

Best wishes,
Egor

**Comment by hchetia** [comment]
Thanks for your help, Egor.
