### ISSUE TITLE
PROBLEMS WITH VARIANT CATALOG

### ISSUE THREAD

**Issue by Gedofs** [Illumina/REViewer#68]
Hi! When running the programme i get this error: [2024-12-17 16:21:50.579] [error] the option '--catalog' is required but missing. 
It seems that i installed ExpansionHunter sucessfully. However i still get this message even if i write the path to the variant catalog json file. Is there any reason why this happens?

Cheers

**Comment by sclamons** [comment]
Hi Gerardo,

Can you post a an example of a script that gets that error?

**Comment by Gedofs** [comment]
Sure!
(base) gerardo@Gerardos-MacBook-Pro bin % ./REViewer \ --reads /Users/gerardo/expansionhunter/example/output/repeats5_realigned.bam \ --vcf /Users/gerardo/expansionhunter/example/output/repeats5.vcf \ --reference /Users/gerardo/expansionhunter/example/input/sequence.fasta \ --catalog /Users/gerardo/expansionhunter/example/output/repeats5.json \ --locus X:67545316-67545385 \ --output-prefix resultado
[2024-12-17 16:30:35.315] [error] the option '--catalog' is required but missing

**Comment by Gedofs** [comment]
I was able to solve this issue by making some changes in the command. However im facing another problem: (base) gerardo@Gerardos-MacBook-Pro bin % ./REViewer --reads /Users/gerardo/expansionhunter/example/output/repeats5_realigned.bam --vcf /Users/gerardo/expansionhunter/example/output/repeats5.vcf --reference /Users/gerardo/expansionhunter/example/input/sequence.fasta --catalog /Users/gerardo/REViewer-0.2.7/reviewer/tests/inputs/catalogs/variant_catalog.json --locus X:67545316-67545385  --output-prefix repeats5 
[2024-12-23 10:57:40.808] [error] Invalid contig name 12

**Comment by Gedofs** [comment]
Thanks! I finally could solve it. this issues were mostly related with the formats. 

I have to say this is a great tool :)
